language: go
sudo: false
go:
  - 1.7
addons:
  apt:
    packages:
      rpm
install:
  - gem install fpm
script:
  - make test_travis
  - make rpm

before_deploy:
  - export PACKAGE_NAME=$(ls build/ditrace-*.x86_64.rpm | tail -n1)
deploy:
  - provider: script
    script: "curl -sS --fail -F \"uploadfile=@${PACKAGE_NAME}\" -H 'token: ${UPLOAD_TOKEN}' \"${UPLOAD_URL}\""
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_GO_VERSION = 1.7
  - provider: script
    script: "curl -sS --fail -F \"uploadfile=@${PACKAGE_NAME}\" -H 'token: ${UPLOAD_TOKEN}' \"${UPLOAD_URL}\""
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION = 1.7

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d5b3776e2e2f89228e0
    on_success: change
    on_failure: always
    on_start: never
